//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknolojiMarketimWithMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSATINALIM
    {
        public int SATINALIMID { get; set; }
        public Nullable<int> SATILANURUN { get; set; }
        public Nullable<int> SATINALANMUSTERI { get; set; }
    
        public virtual TBLMUSTERI TBLMUSTERI { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
