//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknolojiMarketimWithMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYORUM
    {
        public int YORUMID { get; set; }
        public string YORUMBASLIK { get; set; }
        public string YORUMMETIN { get; set; }
        public string YORUMYAZAN { get; set; }
        public string YORUMMAIL { get; set; }
        public Nullable<int> YORUNURUN { get; set; }
    
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
